name: clockify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  vit_dart_extensions: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
